HR_project/config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :qualifications
  resources :attendences
  resources :employees
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

HR_project/app/models/attendence.rb
class Attendence < ApplicationRecord
  belongs_to :employee
end

HR_project/app/controllers/attendences_controller.rb
class AttendencesController < ApplicationController
  before_action :set_attendence, only: [:show, :edit, :update, :destroy]

  # GET /attendences
  # GET /attendences.json
  def index
    @attendences = Attendence.all
  end

  # GET /attendences/1
  # GET /attendences/1.json
  def show
  end

  # GET /attendences/new
  def new
    @attendence = Attendence.new
    @employees = Employee.all
  end

  # GET /attendences/1/edit
  def edit
    @employees = Employee.all
  end

  # POST /attendences
  # POST /attendences.json
  def create
    @attendence = Attendence.new(attendence_params)

    respond_to do |format|
      if @attendence.save
        format.html { redirect_to @attendence, notice: 'Attendence was successfully created.' }
        format.json { render :show, status: :created, location: @attendence }
      else
        format.html { render :new }
        format.json { render json: @attendence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendences/1
  # PATCH/PUT /attendences/1.json
  def update
    respond_to do |format|
      if @attendence.update(attendence_params)
        format.html { redirect_to @attendence, notice: 'Attendence was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendence }
      else
        format.html { render :edit }
        format.json { render json: @attendence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendences/1
  # DELETE /attendences/1.json
  def destroy
    @attendence.destroy
    respond_to do |format|
      format.html { redirect_to attendences_url, notice: 'Attendence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendence
      @attendence = Attendence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendence_params
      params.require(:attendence).permit(:present_or_absent, :date_and_time_of_entry, :date_and_time_of_exit, :employee_id)
    end
end

HR_project/app/helpers/attendences_helper.rb
module AttendencesHelper
end

HR_project/app/views/attendences/_form.html.erb
<%= form_for(attendence) do |f| %>
  <% if attendence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendence.errors.count, "error") %> prohibited this attendence from being saved:</h2>

      <ul>
      <% attendence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <%= f.label :employee_id %>
    <%= f.collection_select(:employee_id, @employees, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :present_or_absent %>
    <%= f.text_field :present_or_absent %>
  </div>

  <div class="field">
    <%= f.label :date_and_time_of_entry %>
    <%= f.datetime_select :date_and_time_of_entry %>
  </div>

  <div class="field">
    <%= f.label :date_and_time_of_exit %>
    <%= f.datetime_select :date_and_time_of_exit %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HR_project/app/views/attendences/edit.html.erb
<h1>Editing Attendence</h1>

<%= render 'form', attendence: @attendence %>

<%= link_to 'Show', @attendence %> |
<%= link_to 'Back', attendences_path %>

HR_project/app/views/attendences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendences</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Present or absent</th>
      <th>Date and time of entry</th>
      <th>Date and time of exit</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendences.each do |attendence| %>
      <tr>
        <td><%= attendence.employee.name %></td>
        <td><%= attendence.present_or_absent %></td>
        <td><%= attendence.date_and_time_of_entry %></td>
        <td><%= attendence.date_and_time_of_exit %></td>
        
        <td><%= link_to 'Show', attendence %></td>
        <td><%= link_to 'Edit', edit_attendence_path(attendence) %></td>
        <td><%= link_to 'Destroy', attendence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendence', new_attendence_path %>

HR_project/app/views/attendences/new.html.erb
<h1>New Attendence</h1>

<%= render 'form', attendence: @attendence %>

<%= link_to 'Back', attendences_path %>

HR_project/app/views/attendences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Present or absent:</strong>
  <%= @attendence.present_or_absent %>
</p>

<p>
  <strong>Date and time of entry:</strong>
  <%= @attendence.date_and_time_of_entry %>
</p>

<p>
  <strong>Date and time of exit:</strong>
  <%= @attendence.date_and_time_of_exit %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @attendence.employee %>
</p>

<%= link_to 'Edit', edit_attendence_path(@attendence) %> |
<%= link_to 'Back', attendences_path %>