HR_project/config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :qualifications
  resources :attendences
  resources :employees
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

HR_project/app/models/qualification.rb
class Qualification < ApplicationRecord
  belongs_to :employee
  
end

HR_project/app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController
  before_action :set_qualification, only: [:show, :edit, :update, :destroy]

  # GET /qualifications
  # GET /qualifications.json
  def index
    @qualifications = Qualification.all
  end

  # GET /qualifications/1
  # GET /qualifications/1.json
  def show
  end

  # GET /qualifications/new
  def new
    @qualification = Qualification.new
    @employees = Employee.all
  end

  # GET /qualifications/1/edit
  def edit
  end

  # POST /qualifications
  # POST /qualifications.json
  def create
    @qualification = Qualification.new(qualification_params)
    # @employees = Employee.all
    respond_to do |format|
      if @qualification.save
        format.html { redirect_to @qualification, notice: 'Qualification was successfully created.' }
        format.json { render :show, status: :created, location: @qualification }
      else
        format.html { render :new }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualifications/1
  # PATCH/PUT /qualifications/1.json
  def update
    respond_to do |format|
      if @qualification.update(qualification_params)
        format.html { redirect_to @qualification, notice: 'Qualification was successfully updated.' }
        format.json { render :show, status: :ok, location: @qualification }
      else
        format.html { render :edit }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualifications/1
  # DELETE /qualifications/1.json
  def destroy
    @qualification.destroy
    respond_to do |format|
      format.html { redirect_to qualifications_url, notice: 'Qualification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualification
      @qualification = Qualification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qualification_params
      params.require(:qualification).permit(:high_school_percentage, :intermediate_percentage, :graduation_course, :graduation_percentage, :graduation_passing_year, :employee_id)
    end
end

HR_project/app/helpers/qualifications_helper.rb
module QualificationsHelper
end

HR_project/app/views/qualifications/_form.html.erb
<%= form_for(qualification) do |f| %>
  <% if qualification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qualification.errors.count, "error") %> prohibited this qualification from being saved:</h2>

      <ul>
      <% qualification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :employee_name %>
    <%= f.collection_select :employee_id, @employees, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :high_school_percentage %>
    <%= f.text_field :high_school_percentage %>
  </div>

  <div class="field">
    <%= f.label :intermediate_percentage %>
    <%= f.text_field :intermediate_percentage %>
  </div>

  <div class="field">
    <%= f.label :graduation_course %>
    <%= f.text_field :graduation_course %>
  </div>

  <div class="field">
    <%= f.label :graduation_percentage %>
    <%= f.text_field :graduation_percentage %>
  </div>

  <div class="field">
    <%= f.label :graduation_passing_year %>
    <%= f.number_field :graduation_passing_year %>
  </div>

  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HR_project/app/views/qualifications/edit.html.erb
<h1>Editing Qualification</h1>

<%= render 'form', qualification: @qualification %>

<%= link_to 'Show', @qualification %> |
<%= link_to 'Back', qualifications_path %>

HR_project/app/views/qualifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qualifications</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>High school percentage</th>
      <th>Intermediate percentage</th>
      <th>Graduation course</th>
      <th>Graduation percentage</th>
      <th>Graduation passing year</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qualifications.each do |qualification| %>
      <tr>
        <td><%= qualification.employee.name %></td>
        <td><%= qualification.high_school_percentage %></td>
        <td><%= qualification.intermediate_percentage %></td>
        <td><%= qualification.graduation_course %></td>
        <td><%= qualification.graduation_percentage %></td>
        <td><%= qualification.graduation_passing_year %></td>
        
        <td><%= link_to 'Show', qualification %></td>
        <td><%= link_to 'Edit', edit_qualification_path(qualification) %></td>
        <td><%= link_to 'Destroy', qualification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qualification', new_qualification_path %>

HR_project/app/views/qualifications/new.html.erb
|| <%= link_to "New employee", new_employee_path %>
<h1>New Qualification</h1>

<%= render 'form', qualification: @qualification %>

<%= link_to 'Back', qualifications_path %>

HR_project/app/views/qualifications/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Employee:</strong>
  <%= @qualification.employee.name %>
</p>
<p>
  <strong>High school percentage:</strong>
  <%= @qualification.high_school_percentage %>
</p>

<p>
  <strong>Intermediate percentage:</strong>
  <%= @qualification.intermediate_percentage %>
</p>

<p>
  <strong>Graduation course:</strong>
  <%= @qualification.graduation_course %>
</p>

<p>
  <strong>Graduation percentage:</strong>
  <%= @qualification.graduation_percentage %>
</p>

<p>
  <strong>Graduation passing year:</strong>
  <%= @qualification.graduation_passing_year %>
</p>



<%= link_to 'Edit', edit_qualification_path(@qualification) %> |
<%= link_to 'Back', qualifications_path %>